-- ============================================================================
-- 0008 — Auditoria (audit_logs) + soft delete
--
--   * audit_logs: registro imutável p/ ações sensíveis. Inserts SÓ via trigger
--     SECURITY DEFINER (authenticated não escreve direto). Leitura: owner/admin.
--   * soft delete em calls e closers (deleted_at / deleted_by). SELECT padrão
--     esconde deletados, exceto owner/admin (restauração).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- audit_logs
-- ---------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id              bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete set null,
  user_id         uuid references auth.users(id) on delete set null,
  action          text not null,           -- INSERT | UPDATE | DELETE
  entity_type     text not null,           -- nome da tabela
  entity_id       uuid,
  old_data        jsonb,
  new_data        jsonb,
  created_at      timestamptz not null default now()
);
create index if not exists idx_audit_org_created on public.audit_logs(organization_id, created_at desc);
create index if not exists idx_audit_entity      on public.audit_logs(entity_type, entity_id);

alter table public.audit_logs enable row level security;

drop policy if exists audit_select on public.audit_logs;
create policy audit_select on public.audit_logs for select to authenticated
  using ( public.has_org_role(organization_id, array['owner','admin']) );
-- (sem insert/update/delete p/ authenticated -> imutável; só trigger/service_role)

-- Função genérica de auditoria. Lê organization_id e id da própria linha.
create or replace function public.audit_trigger()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_org uuid;
  v_old jsonb;
  v_new jsonb;
  v_entity uuid;
begin
  if (tg_op = 'DELETE') then
    v_old := to_jsonb(old); v_new := null;
    v_org := nullif(v_old->>'organization_id','')::uuid;
    v_entity := nullif(v_old->>'id','')::uuid;
  elsif (tg_op = 'INSERT') then
    v_old := null; v_new := to_jsonb(new);
    v_org := nullif(v_new->>'organization_id','')::uuid;
    v_entity := nullif(v_new->>'id','')::uuid;
  else
    v_old := to_jsonb(old); v_new := to_jsonb(new);
    v_org := nullif(v_new->>'organization_id','')::uuid;
    v_entity := nullif(v_new->>'id','')::uuid;
  end if;

  insert into public.audit_logs (organization_id, user_id, action, entity_type, entity_id, old_data, new_data)
  values (v_org, auth.uid(), tg_op, tg_table_name, v_entity, v_old, v_new);

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

-- Auditar mudanças de permissão (membros) e de status (calls, ações).
drop trigger if exists trg_audit_org_members on public.organization_members;
create trigger trg_audit_org_members
  after insert or update or delete on public.organization_members
  for each row execute function public.audit_trigger();

drop trigger if exists trg_audit_calls_status on public.calls;
create trigger trg_audit_calls_status
  after update on public.calls
  for each row
  when (old.status is distinct from new.status)
  execute function public.audit_trigger();

drop trigger if exists trg_audit_actions_status on public.improvement_actions;
create trigger trg_audit_actions_status
  after update on public.improvement_actions
  for each row
  when (old.status is distinct from new.status)
  execute function public.audit_trigger();

-- ---------------------------------------------------------------------------
-- Soft delete (calls, closers)
-- ---------------------------------------------------------------------------
alter table public.calls   add column if not exists deleted_at timestamptz;
alter table public.calls   add column if not exists deleted_by uuid references auth.users(id) on delete set null;
alter table public.closers add column if not exists deleted_at timestamptz;
alter table public.closers add column if not exists deleted_by uuid references auth.users(id) on delete set null;

create index if not exists idx_calls_org_deleted   on public.calls(organization_id, deleted_at);
create index if not exists idx_closers_org_deleted on public.closers(organization_id, deleted_at);

-- Recria SELECT escondendo deletados (exceto owner/admin para restaurar)
drop policy if exists calls_select on public.calls;
create policy calls_select on public.calls for select to authenticated
  using (
    public.is_org_member(organization_id)
    and (deleted_at is null or public.has_org_role(organization_id, array['owner','admin']))
  );

drop policy if exists closers_select on public.closers;
create policy closers_select on public.closers for select to authenticated
  using (
    public.is_org_member(organization_id)
    and (deleted_at is null or public.has_org_role(organization_id, array['owner','admin']))
  );
